import { Platform, StyleSheet } from 'react-native';

const createStyles = (COLORS: any) =>
    StyleSheet.create({
        safe: {
            flex: 1,
            backgroundColor: COLORS.background,
        },
        center: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: COLORS.background,
        },
        errorText: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 15,
            color: COLORS.error,
        },
        scroll: {
            padding: 20,
            gap: 16,
            paddingBottom: 40,
        },
        infoSection: {
            gap: 4,
        },
        infoTitle: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 24,
            color: COLORS.textPrimary,
        },
        infoSubtitle: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 13,
            color: COLORS.textSecondary,
        },
        emptyCard: {
            alignItems: 'center',
            gap: 12,
            paddingVertical: 48,
            paddingHorizontal: 32,
        },
        emptyTitle: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 18,
            color: COLORS.textPrimary,
        },
        emptyHint: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 14,
            color: COLORS.textSecondary,
            textAlign: 'center',
            lineHeight: 22,
        },
        goalCard: {
            backgroundColor: COLORS.white,
            borderRadius: 20,
            padding: 20,
            gap: 12,
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 1 },
            shadowOpacity: 0.06,
            shadowRadius: 6,
            elevation: 2,
        },
        goalTop: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
        },
        goalIconBox: {
            width: 32,
            height: 32,
            borderRadius: 10,
            backgroundColor: COLORS.primary,
            alignItems: 'center',
            justifyContent: 'center',
            flexShrink: 0,
        },
        goalIconBoxCompleted: {
            backgroundColor: '#43A047',
        },
        goalIconBoxExpired: {
            backgroundColor: '#E65100',
        },
        goalTitle: {
            flex: 1,
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 16,
            color: COLORS.textPrimary,
        },
        deadlineText: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 12,
            color: COLORS.textSecondary,
        },
        deadlineTextExpired: {
            color: '#E65100',
        },
        expiredBadge: {
            backgroundColor: '#FBE9E7',
            borderRadius: 10,
            paddingHorizontal: 8,
            paddingVertical: 3,
            marginLeft: 6,
        },
        expiredBadgeText: {
            color: '#E65100',
            fontSize: 11,
            fontFamily: 'HankenGrotesk_500Medium',
        },
        amountRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        amountLeft: {
            flexDirection: 'row',
            alignItems: 'baseline',
        },
        currentAmount: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 26,
            color: COLORS.textPrimary,
        },
        targetAmount: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 14,
            color: COLORS.textSecondary,
        },
        pctText: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 13,
            color: COLORS.primary,
        },
        pctTextCompleted: {
            color: '#43A047',
        },
        pctTextExpired: {
            color: '#E65100',
        },
        progressTrack: {
            height: 8,
            backgroundColor: COLORS.surfaceContainerHigh,
            borderRadius: 4,
            overflow: 'hidden',
        },
        progressFill: {
            height: 8,
            backgroundColor: COLORS.primary,
            borderRadius: 4,
        },
        progressFillCompleted: {
            backgroundColor: '#43A047',
        },
        progressFillExpired: {
            backgroundColor: '#E65100',
        },
        aiCard: {
            backgroundColor: COLORS.textPrimary,
            borderRadius: 16,
            padding: 16,
            gap: 10,
        },
        aiCardEmpty: {
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
        },
        aiHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
        },
        aiLabel: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 12,
            color: COLORS.primary,
        },
        aiMessage: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 13,
            lineHeight: 20,
            color: 'rgba(255,255,255,0.85)',
            flex: 1,
        },
        aiEmptyText: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 12,
            color: COLORS.textSecondary,
            textAlign: 'center',
        },
        aiBtn: {
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: COLORS.primary,
            borderRadius: 10,
            paddingVertical: 9,
        },
        aiBtnText: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 13,
            color: COLORS.white,
        },
        addBtn: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: COLORS.primary,
            alignItems: 'center',
            justifyContent: 'center',
        },
        headerBtnWrap: {
            marginRight: 16,
        },
        spacer: {
            width: 36,
        },
        detailOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.4)',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 24,
        },
        detailCard: {
            width: '100%',
            backgroundColor: COLORS.white,
            borderRadius: 28,
            paddingBottom: 28,
            overflow: 'hidden',
        },
        detailHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 14,
        },
        detailCloseBtn: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: COLORS.surfaceContainerLow,
            alignItems: 'center',
            justifyContent: 'center',
        },
        detailTitle: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 17,
            color: COLORS.textPrimary,
        },
        detailIconWrap: {
            width: 72,
            height: 72,
            borderRadius: 36,
            backgroundColor: COLORS.primary,
            alignSelf: 'center',
            alignItems: 'center',
            justifyContent: 'center',
            marginVertical: 8,
        },
        detailIconWrapCompleted: {
            backgroundColor: '#43A047',
        },
        detailIconWrapExpired: {
            backgroundColor: '#E65100',
        },
        detailGoalName: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 20,
            color: COLORS.textPrimary,
            textAlign: 'center',
            paddingHorizontal: 24,
            marginTop: 4,
        },
        detailStatusBadge: {
            alignSelf: 'center',
            backgroundColor: COLORS.primaryContainer,
            borderRadius: 20,
            paddingHorizontal: 12,
            paddingVertical: 4,
            marginTop: 6,
            marginBottom: 16,
        },
        detailStatusBadgeCompleted: {
            backgroundColor: '#E8F5E9',
        },
        detailStatusBadgeExpired: {
            backgroundColor: '#FBE9E7',
        },
        detailStatusText: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 12,
            color: COLORS.primary,
        },
        detailStatusTextCompleted: {
            color: '#388E3C',
        },
        detailStatusTextExpired: {
            color: '#E65100',
        },
        detailProgressTrack: {
            height: 8,
            backgroundColor: COLORS.surfaceContainerHigh,
            borderRadius: 4,
            overflow: 'hidden',
            marginHorizontal: 24,
        },
        detailProgressFill: {
            height: 8,
            backgroundColor: COLORS.primary,
            borderRadius: 4,
        },
        detailProgressFillCompleted: {
            backgroundColor: '#43A047',
        },
        detailProgressFillExpired: {
            backgroundColor: '#E65100',
        },
        detailPctText: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 13,
            color: COLORS.primary,
            textAlign: 'center',
            marginTop: 6,
            marginBottom: 16,
        },
        detailInfoRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
            paddingHorizontal: 28,
            paddingVertical: 8,
        },
        detailInfoText: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 14,
            color: COLORS.textPrimary,
            flex: 1,
        },
        detailDeleteBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            marginHorizontal: 28,
            marginTop: 20,
            paddingVertical: 14,
            borderRadius: 14,
            borderWidth: 1.5,
            borderColor: COLORS.error,
        },
        detailDeleteText: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 15,
            color: COLORS.error,
        },
        addSafe: {
            flex: 1,
            backgroundColor: COLORS.background,
        },
        addFlex: {
            flex: 1,
        },
        addHeader: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 20,
            paddingVertical: 14,
            paddingTop: 0,
        },
        addHeaderTitle: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 17,
            color: COLORS.textPrimary,
        },
        addContent: {
            paddingHorizontal: 20,
            paddingBottom: 24,
            gap: 4,
        },
        addFieldLabel: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 13,
            color: COLORS.textSecondary,
            marginTop: 16,
            marginBottom: 8,
            letterSpacing: 0.3,
        },
        addTextInput: {
            backgroundColor: COLORS.surfaceContainerLow,
            borderRadius: 14,
            paddingHorizontal: 14,
            paddingVertical: Platform.OS === 'ios' ? 14 : 10,
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 15,
            color: COLORS.textPrimary,
        },
        addAmountRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            paddingVertical: 20,
        },
        addAmountSymbol: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 32,
            color: COLORS.textSecondary,
        },
        addAmountInput: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 48,
            color: COLORS.textPrimary,
            minWidth: 120,
            textAlign: 'center',
        },
        addDateRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            backgroundColor: COLORS.surfaceContainerLow,
            borderRadius: 14,
            paddingHorizontal: 14,
            paddingVertical: 12,
        },
        addDateArrow: {
            padding: 2,
        },
        addDateText: {
            flex: 1,
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 15,
            color: COLORS.textPrimary,
            textAlign: 'center',
        },
        addFormError: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 13,
            color: COLORS.error,
            marginTop: 4,
        },
        addSaveWrap: {
            paddingHorizontal: 20,
            paddingVertical: 12,
        },
        addSaveBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: COLORS.primary,
            borderRadius: 16,
            paddingVertical: 16,
        },
        addSaveBtnDisabled: {
            opacity: 0.6,
        },
        addSaveBtnText: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 16,
            color: COLORS.white,
        },
    });

export default createStyles;
