import { StyleSheet } from 'react-native';

const createStyles = (COLORS: any) =>
    StyleSheet.create({
        safe: {
            flex: 1,
            backgroundColor: COLORS.background,
        },
        header: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 16,
            paddingVertical: 12,
        },
        backBtn: {
            width: 40,
            height: 40,
            alignItems: 'center',
            justifyContent: 'center',
        },
        headerTitle: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 18,
            color: COLORS.textPrimary,
        },
        addBtn: {
            width: 40,
            height: 40,
            borderRadius: 20,
            backgroundColor: COLORS.primary,
            alignItems: 'center',
            justifyContent: 'center',
        },
        center: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
        },
        scroll: {
            padding: 20,
            paddingBottom: 40,
        },
        emptyCard: {
            backgroundColor: COLORS.white,
            borderRadius: 24,
            padding: 32,
            alignItems: 'center',
            justifyContent: 'center',
            gap: 12,
            marginTop: 20,
        },
        emptyTitle: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 18,
            color: COLORS.textPrimary,
        },
        emptyHint: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 14,
            color: COLORS.textSecondary,
            textAlign: 'center',
            lineHeight: 20,
        },
        recCard: {
            backgroundColor: COLORS.white,
            borderRadius: 24,
            padding: 16,
            marginBottom: 12,
        },
        recCardInactive: {
            opacity: 0.6,
        },
        recCardContent: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
        },
        recInfo: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            gap: 12,
        },
        recIconBox: {
            width: 44,
            height: 44,
            borderRadius: 22,
            backgroundColor: COLORS.surfaceContainerLow,
            alignItems: 'center',
            justifyContent: 'center',
        },
        recIconExpense: {
            backgroundColor: COLORS.primary,
        },
        recIconIncome: {
            backgroundColor: COLORS.primary,
        },
        recDesc: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 16,
            color: COLORS.textPrimary,
            marginBottom: 2,
        },
        recCat: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 13,
            color: COLORS.textSecondary,
        },
        recAmount: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 16,
        },
        recAmountExpense: {
            color: '#E53935',
        },
        recAmountIncome: {
            color: '#2E7D32',
        },
        recTextWrap: {
            flex: 1,
            paddingRight: 8,
        },
        recRight: {
            alignItems: 'flex-end',
            gap: 4,
        },
        recRightBottom: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 6,
        },
        recDetailItem: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 4,
        },
        recDetailTextDate: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 12,
            color: COLORS.textSecondary,
        },
        recSwitch: {
            transform: [{ scaleX: 0.65 }, { scaleY: 0.65 }],
            marginRight: -6,
            marginLeft: -4,
        },
        // Modal Styles
        modalSafe: {
            flex: 1,
            backgroundColor: COLORS.background,
        },
        flex: {
            flex: 1,
        },
        modalHeader: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 20,
            paddingVertical: 14,
            paddingTop: 0,
        },
        modalTitle: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 17,
            color: COLORS.textPrimary,
        },
        spacer: {
            width: 36,
        },
        modalScroll: {
            flex: 1,
        },
        modalContent: {
            paddingHorizontal: 20,
            paddingBottom: 24,
            gap: 4,
        },
        typeToggle: {
            flexDirection: 'row',
            backgroundColor: COLORS.surfaceContainerLow,
            borderRadius: 16,
            padding: 4,
            marginBottom: 8,
        },
        typeBtn: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 6,
            paddingVertical: 10,
            borderRadius: 12,
        },
        typeBtnActiveExpense: {
            backgroundColor: COLORS.white,
        },
        typeBtnActiveIncome: {
            backgroundColor: COLORS.white,
        },
        typeDot: {
            width: 8,
            height: 8,
            borderRadius: 4,
        },
        typeBtnText: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 14,
            color: COLORS.textSecondary,
        },
        typeBtnTextActive: {
            color: '#E53935',
        },
        typeBtnTextActiveIncome: {
            color: '#2E7D32',
        },
        amountRow: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            paddingVertical: 20,
        },
        amountSymbol: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 32,
            color: COLORS.textSecondary,
        },
        amountInput: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 48,
            color: COLORS.textPrimary,
            minWidth: 120,
            textAlign: 'center',
        },
        fieldLabel: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 13,
            color: COLORS.textSecondary,
            marginTop: 16,
            marginBottom: 8,
            letterSpacing: 0.3,
        },
        catGrid: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            gap: 8,
        },
        catChip: {
            alignItems: 'center',
            gap: 4,
            backgroundColor: COLORS.primaryContainer,
            borderRadius: 14,
            paddingVertical: 12,
        },
        catChipSelected: {
            backgroundColor: COLORS.primary,
        },
        catChipText: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 13,
            color: COLORS.primary,
        },
        catChipTextSelected: {
            color: COLORS.white,
        },
        descRow: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: COLORS.surfaceContainerLow,
            borderRadius: 14,
            paddingHorizontal: 14,
            paddingVertical: 12,
            gap: 8,
        },
        descInput: {
            flex: 1,
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 15,
            color: COLORS.textPrimary,
        },
        dateRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            backgroundColor: COLORS.surfaceContainerLow,
            borderRadius: 14,
            paddingHorizontal: 14,
            paddingVertical: 12,
        },
        dateArrow: {
            padding: 2,
        },
        dateText: {
            flex: 1,
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 15,
            color: COLORS.textPrimary,
            textAlign: 'center',
        },
        intervalRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            gap: 8,
        },
        intervalBtn: {
            flex: 1,
            backgroundColor: COLORS.surfaceContainerLow,
            borderRadius: 12,
            paddingVertical: 10,
            alignItems: 'center',
        },
        intervalBtnSelected: {
            backgroundColor: COLORS.primary,
        },
        intervalBtnText: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 13,
            color: COLORS.textPrimary,
        },
        intervalBtnTextSelected: {
            color: COLORS.white,
        },
        saveWrap: {
            paddingHorizontal: 20,
            paddingTop: 12,
            paddingBottom: 20,
        },
        saveBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            backgroundColor: COLORS.primary,
            borderRadius: 16,
            paddingVertical: 16,
        },
        saveBtnDisabled: {
            opacity: 0.6,
        },
        saveBtnText: {
            fontFamily: 'HankenGrotesk_600SemiBold',
            fontSize: 16,
            color: COLORS.white,
        },
        detailOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0,0,0,0.4)',
            justifyContent: 'center',
            alignItems: 'center',
            padding: 24,
        },
        detailCard: {
            width: '100%',
            backgroundColor: COLORS.white,
            borderRadius: 28,
            paddingBottom: 28,
            overflow: 'hidden',
        },
        detailHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 14,
        },
        detailCloseBtn: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: COLORS.surfaceContainerLow,
            alignItems: 'center',
            justifyContent: 'center',
        },
        detailIconWrap: {
            width: 72,
            height: 72,
            borderRadius: 36,
            alignSelf: 'center',
            alignItems: 'center',
            justifyContent: 'center',
            marginVertical: 8,
        },
        detailAmount: {
            fontFamily: 'HankenGrotesk_700Bold',
            fontSize: 36,
            textAlign: 'center',
            marginTop: 8,
        },
        detailType: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 14,
            color: COLORS.textSecondary,
            textAlign: 'center',
            marginTop: 4,
            marginBottom: 20,
        },
        detailRow: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 10,
            paddingHorizontal: 28,
            paddingVertical: 8,
        },
        detailRowText: {
            fontFamily: 'HankenGrotesk_400Regular',
            fontSize: 14,
            color: COLORS.textPrimary,
            flex: 1,
        },
        detailDeleteBtn: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            gap: 8,
            marginHorizontal: 28,
            marginTop: 24,
            paddingVertical: 14,
            borderRadius: 14,
            borderWidth: 1.5,
            borderColor: COLORS.error,
        },
        detailDeleteText: {
            fontFamily: 'HankenGrotesk_500Medium',
            fontSize: 15,
            color: COLORS.error,
        },
    });

export default createStyles;
