import { StyleSheet } from 'react-native';
import { COLORS, TYPOGRAPHY } from '../../constants/theme';

export default StyleSheet.create({
  // ─── Screen ───────────────────────────────────────────────────────────────────
  safe: { flex: 1, backgroundColor: COLORS.background },
  flex: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 },
  emptyText: { ...TYPOGRAPHY.bodyMd, color: COLORS.textSecondary, marginTop: 8 },
  emptySubText: {
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 14,
    color: COLORS.placeholderText,
  },

  // ─── Header ───────────────────────────────────────────────────────────────────
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginRight: 16,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── List ─────────────────────────────────────────────────────────────────────
  listContent: { paddingHorizontal: 20, paddingBottom: 24 },
  sectionHeader: {
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 20,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  txRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 8,
    gap: 12,
  },
  txIcon: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  txIconIncome: {},
  txInfo: { flex: 1 },
  txDesc: {
    fontFamily: 'HankenGrotesk_500Medium',
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  txMeta: {
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  txAmount: { fontFamily: 'HankenGrotesk_600SemiBold', fontSize: 15 },
  amountExpense: { color: '#E53935' },
  amountIncome: { color: '#2E7D32' },

  // ─── Shared modal ─────────────────────────────────────────────────────────────
  modalSafe: { flex: 1, backgroundColor: COLORS.background },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.surfaceContainerLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 17,
    color: COLORS.textPrimary,
  },
  modalContent: { paddingHorizontal: 20, paddingBottom: 24, gap: 4 },

  // ─── Add modal form ───────────────────────────────────────────────────────────
  typeToggle: {
    flexDirection: 'row',
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 16,
    padding: 4,
    marginBottom: 8,
  },
  typeBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
  },
  typeBtnActiveExpense: { backgroundColor: COLORS.white },
  typeBtnActiveIncome: { backgroundColor: COLORS.white },
  typeDot: { width: 8, height: 8, borderRadius: 4 },
  typeBtnText: {
    fontFamily: 'HankenGrotesk_500Medium',
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  typeBtnTextActive: { color: '#E53935' },
  typeBtnTextActiveIncome: { color: '#2E7D32' },

  amountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 20,
  },
  amountSymbol: {
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 32,
    color: COLORS.textSecondary,
  },
  amountInput: {
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 48,
    color: COLORS.textPrimary,
    minWidth: 120,
    textAlign: 'center',
  },

  fieldLabel: {
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 16,
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  catGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  catChip: {
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.primaryContainer,
    borderRadius: 14,
    paddingVertical: 12,
  },
  catChipSelected: { backgroundColor: COLORS.primary },
  catChipText: {
    fontFamily: 'HankenGrotesk_500Medium',
    fontSize: 13,
    color: COLORS.primary,
  },
  catChipTextSelected: { color: COLORS.white },

  descRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  descInput: {
    flex: 1,
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 15,
    color: COLORS.textPrimary,
  },

  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.surfaceContainerLow,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dateArrow: { padding: 2 },
  dateText: {
    flex: 1,
    fontFamily: 'HankenGrotesk_500Medium',
    fontSize: 15,
    color: COLORS.textPrimary,
    textAlign: 'center',
  },

  saveWrap: { paddingHorizontal: 20, paddingVertical: 12 },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    paddingVertical: 16,
  },
  saveBtnDisabled: { opacity: 0.6 },
  saveBtnText: {
    fontFamily: 'HankenGrotesk_600SemiBold',
    fontSize: 16,
    color: COLORS.white,
  },

  spacer: { width: 36 },

  // ─── Detail modal ─────────────────────────────────────────────────────────────
  detailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  detailCard: {
    width: '100%',
    backgroundColor: COLORS.white,
    borderRadius: 28,
    paddingBottom: 28,
    overflow: 'hidden',
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  detailIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 8,
  },
  detailIconExpense: { backgroundColor: COLORS.primary },
  detailIconIncome: { backgroundColor: '#2E7D32' },
  detailAmount: {
    fontFamily: 'HankenGrotesk_700Bold',
    fontSize: 36,
    textAlign: 'center',
    marginTop: 8,
  },
  detailType: {
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 28,
    paddingVertical: 8,
  },
  detailRowText: {
    fontFamily: 'HankenGrotesk_400Regular',
    fontSize: 14,
    color: COLORS.textPrimary,
    flex: 1,
  },
  detailDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 28,
    marginTop: 24,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.error,
  },
  detailDeleteText: {
    fontFamily: 'HankenGrotesk_500Medium',
    fontSize: 15,
    color: COLORS.error,
  },
});
